# Generated by Django 4.0.5 on 2022-06-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museum', to='main_app.painting')),
            ],
        ),
    ]
