# Generated by Django 4.0.5 on 2022-06-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_museum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museumschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('museums', models.ManyToManyField(to='main_app.museum')),
            ],
        ),
    ]
